version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=postgresql://iaps:iaps@db:5432/iaps
      - PYTHONPATH=/app
    depends_on:
      - db
    volumes:
      - .:/app
    command: uvicorn iaps.api.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=iaps
      - POSTGRES_PASSWORD=iaps
      - POSTGRES_DB=iaps
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 